# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'field-workers.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(445, 345)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 411, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.controller_responsability = QtWidgets.QComboBox(Dialog)
        self.controller_responsability.setGeometry(QtCore.QRect(30, 100, 171, 22))
        self.controller_responsability.setObjectName("controller_responsability")
        self.controller_responsability.addItem("")
        self.controller_responsability.addItem("")
        self.controller_responsability.addItem("")
        self.role = QtWidgets.QComboBox(Dialog)
        self.role.setGeometry(QtCore.QRect(240, 100, 181, 22))
        self.role.setObjectName("role")
        self.role.addItem("")
        self.role.addItem("")
        self.role.addItem("")
        self.role.addItem("")
        self.role.addItem("")
        self.role.addItem("")
        self.operational_status = QtWidgets.QComboBox(Dialog)
        self.operational_status.setGeometry(QtCore.QRect(240, 150, 181, 22))
        self.operational_status.setObjectName("operational_status")
        self.operational_status.addItem("")
        self.operational_status.addItem("")
        self.operational_status.addItem("")
        self.operational_status.addItem("")
        self.logout = QtWidgets.QPushButton(Dialog)
        self.logout.setGeometry(QtCore.QRect(230, 300, 93, 28))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(9)
        self.logout.setFont(font)
        self.logout.setObjectName("logout")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 180, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 130, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 80, 191, 16))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(240, 80, 55, 16))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(240, 130, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.login = QtWidgets.QPushButton(Dialog)
        self.login.setGeometry(QtCore.QRect(330, 300, 93, 28))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(9)
        self.login.setFont(font)
        self.login.setObjectName("login")
        self.error = QtWidgets.QLabel(Dialog)
        self.error.setGeometry(QtCore.QRect(30, 250, 381, 16))
        self.error.setText("")
        self.error.setObjectName("error")
        self.controller_id_1 = QtWidgets.QComboBox(Dialog)
        self.controller_id_1.setGeometry(QtCore.QRect(30, 150, 171, 22))
        self.controller_id_1.setObjectName("controller_id_1")
        self.controller_id_2 = QtWidgets.QComboBox(Dialog)
        self.controller_id_2.setGeometry(QtCore.QRect(30, 200, 171, 22))
        self.controller_id_2.setObjectName("controller_id_2")
        self.facilityText = QtWidgets.QLabel(Dialog)
        self.facilityText.setGeometry(QtCore.QRect(310, 20, 111, 16))
        self.facilityText.setText("")
        self.facilityText.setObjectName("facilityText")
        self.workstationText = QtWidgets.QLabel(Dialog)
        self.workstationText.setGeometry(QtCore.QRect(30, 50, 171, 16))
        self.workstationText.setText("")
        self.workstationText.setObjectName("workstationText")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "CALS SIM -"))
        self.controller_responsability.setItemText(0, _translate("Dialog", "Planning"))
        self.controller_responsability.setItemText(1, _translate("Dialog", "Tactical"))
        self.controller_responsability.setItemText(2, _translate("Dialog", "Weather"))
        self.role.setItemText(0, _translate("Dialog", "Procedural Enroute"))
        self.role.setItemText(1, _translate("Dialog", "Radar Terminal"))
        self.role.setItemText(2, _translate("Dialog", "Radar Arrivals"))
        self.role.setItemText(3, _translate("Dialog", "Radar Departures"))
        self.role.setItemText(4, _translate("Dialog", "Ground Procedural"))
        self.role.setItemText(5, _translate("Dialog", "Local Procedural"))
        self.operational_status.setItemText(0, _translate("Dialog", "SC"))
        self.operational_status.setItemText(1, _translate("Dialog", "MCM"))
        self.operational_status.setItemText(2, _translate("Dialog", "MCI"))
        self.operational_status.setItemText(3, _translate("Dialog", "MCU"))
        self.logout.setText(_translate("Dialog", "Log Out"))
        self.label_2.setText(_translate("Dialog", "Controller Id 2"))
        self.label_3.setText(_translate("Dialog", "Controller Id 1"))
        self.label_4.setText(_translate("Dialog", "Controller Responsability"))
        self.label_5.setText(_translate("Dialog", "Role"))
        self.label_6.setText(_translate("Dialog", "Operational status"))
        self.login.setText(_translate("Dialog", "Login"))

