# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SimulationWidget.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SimulationWidget(object):
    def setupUi(self, SimulationWidget):
        SimulationWidget.setObjectName(_fromUtf8("SimulationWidget"))
        SimulationWidget.resize(470, 324)
        self.Controller_lbl = QtGui.QLabel(SimulationWidget)
        self.Controller_lbl.setGeometry(QtCore.QRect(20, 60, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Controller_lbl.setFont(font)
        self.Controller_lbl.setObjectName(_fromUtf8("Controller_lbl"))
        self.controllerID_line = QtGui.QLineEdit(SimulationWidget)
        self.controllerID_line.setGeometry(QtCore.QRect(20, 80, 161, 20))
        self.controllerID_line.setObjectName(_fromUtf8("controllerID_line"))
        self.line = QtGui.QFrame(SimulationWidget)
        self.line.setGeometry(QtCore.QRect(0, 40, 471, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.responsibility_lbl = QtGui.QLabel(SimulationWidget)
        self.responsibility_lbl.setGeometry(QtCore.QRect(250, 60, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.responsibility_lbl.setFont(font)
        self.responsibility_lbl.setObjectName(_fromUtf8("responsibility_lbl"))
        self.operational_lbl = QtGui.QLabel(SimulationWidget)
        self.operational_lbl.setGeometry(QtCore.QRect(250, 160, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.operational_lbl.setFont(font)
        self.operational_lbl.setObjectName(_fromUtf8("operational_lbl"))
        self.responsibility_cmbox = QtGui.QComboBox(SimulationWidget)
        self.responsibility_cmbox.setGeometry(QtCore.QRect(250, 80, 161, 22))
        self.responsibility_cmbox.setObjectName(_fromUtf8("responsibility_cmbox"))
        self.responsibility_cmbox.addItem(_fromUtf8(""))
        self.responsibility_cmbox.addItem(_fromUtf8(""))
        self.responsibility_cmbox.addItem(_fromUtf8(""))
        self.operational_cmbox = QtGui.QComboBox(SimulationWidget)
        self.operational_cmbox.setGeometry(QtCore.QRect(250, 180, 161, 22))
        self.operational_cmbox.setObjectName(_fromUtf8("operational_cmbox"))
        self.operational_cmbox.addItem(_fromUtf8(""))
        self.operational_cmbox.addItem(_fromUtf8(""))
        self.operational_cmbox.addItem(_fromUtf8(""))
        self.operational_cmbox.addItem(_fromUtf8(""))
        self.operational_cmbox.addItem(_fromUtf8(""))
        self.operational_cmbox.addItem(_fromUtf8(""))
        self.login_btn = QtGui.QPushButton(SimulationWidget)
        self.login_btn.setGeometry(QtCore.QRect(100, 280, 75, 23))
        self.login_btn.setObjectName(_fromUtf8("login_btn"))
        self.logout_btn = QtGui.QPushButton(SimulationWidget)
        self.logout_btn.setGeometry(QtCore.QRect(190, 280, 75, 23))
        self.logout_btn.setObjectName(_fromUtf8("logout_btn"))
        self.error_lbl = QtGui.QLabel(SimulationWidget)
        self.error_lbl.setGeometry(QtCore.QRect(20, 230, 431, 21))
        self.error_lbl.setText(_fromUtf8(""))
        self.error_lbl.setObjectName(_fromUtf8("error_lbl"))
        self.error_title_label = QtGui.QLabel(SimulationWidget)
        self.error_title_label.setGeometry(QtCore.QRect(20, 210, 171, 20))
        self.error_title_label.setObjectName(_fromUtf8("error_title_label"))
        self.role_change_btn = QtGui.QPushButton(SimulationWidget)
        self.role_change_btn.setGeometry(QtCore.QRect(280, 280, 75, 23))
        self.role_change_btn.setObjectName(_fromUtf8("role_change_btn"))
        self.role_cmbox = QtGui.QComboBox(SimulationWidget)
        self.role_cmbox.setGeometry(QtCore.QRect(250, 130, 161, 22))
        self.role_cmbox.setObjectName(_fromUtf8("role_cmbox"))
        self.role_cmbox.addItem(_fromUtf8(""))
        self.role_cmbox.addItem(_fromUtf8(""))
        self.role_cmbox.addItem(_fromUtf8(""))
        self.role_cmbox.addItem(_fromUtf8(""))
        self.role_cmbox.addItem(_fromUtf8(""))
        self.role_cmbox.addItem(_fromUtf8(""))
        self.label = QtGui.QLabel(SimulationWidget)
        self.label.setGeometry(QtCore.QRect(250, 110, 47, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.title_lbl = QtGui.QLabel(SimulationWidget)
        self.title_lbl.setGeometry(QtCore.QRect(10, -10, 469, 68))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.title_lbl.setFont(font)
        self.title_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.title_lbl.setObjectName(_fromUtf8("title_lbl"))
        self.facility_lbl = QtGui.QLabel(SimulationWidget)
        self.facility_lbl.setGeometry(QtCore.QRect(20, 160, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.facility_lbl.setFont(font)
        self.facility_lbl.setObjectName(_fromUtf8("facility_lbl"))
        self.facility_line = QtGui.QLineEdit(SimulationWidget)
        self.facility_line.setGeometry(QtCore.QRect(20, 180, 161, 20))
        self.facility_line.setObjectName(_fromUtf8("facility_line"))
        self.workstationID_lbl = QtGui.QLabel(SimulationWidget)
        self.workstationID_lbl.setGeometry(QtCore.QRect(20, 110, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.workstationID_lbl.setFont(font)
        self.workstationID_lbl.setObjectName(_fromUtf8("workstationID_lbl"))
        self.workstationID_line = QtGui.QLineEdit(SimulationWidget)
        self.workstationID_line.setGeometry(QtCore.QRect(20, 130, 161, 20))
        self.workstationID_line.setObjectName(_fromUtf8("workstationID_line"))

        self.retranslateUi(SimulationWidget)
        QtCore.QMetaObject.connectSlotsByName(SimulationWidget)

    def retranslateUi(self, SimulationWidget):
        SimulationWidget.setWindowTitle(_translate("SimulationWidget", "Form", None))
        self.Controller_lbl.setText(_translate("SimulationWidget", "Controller ID", None))
        self.responsibility_lbl.setText(_translate("SimulationWidget", "Controller responsibility", None))
        self.operational_lbl.setText(_translate("SimulationWidget", "Operational status", None))
        self.responsibility_cmbox.setItemText(0, _translate("SimulationWidget", "Planning", None))
        self.responsibility_cmbox.setItemText(1, _translate("SimulationWidget", "Tactical", None))
        self.responsibility_cmbox.setItemText(2, _translate("SimulationWidget", "Weather", None))
        self.operational_cmbox.setItemText(0, _translate("SimulationWidget", "SC", None))
        self.operational_cmbox.setItemText(1, _translate("SimulationWidget", "MCU", None))
        self.operational_cmbox.setItemText(2, _translate("SimulationWidget", "MCS", None))
        self.operational_cmbox.setItemText(3, _translate("SimulationWidget", "MCM", None))
        self.operational_cmbox.setItemText(4, _translate("SimulationWidget", "MCT", None))
        self.operational_cmbox.setItemText(5, _translate("SimulationWidget", "MCI", None))
        self.login_btn.setText(_translate("SimulationWidget", "Login", None))
        self.logout_btn.setText(_translate("SimulationWidget", "Logout", None))
        self.error_title_label.setText(_translate("SimulationWidget", "Error Message", None))
        self.role_change_btn.setText(_translate("SimulationWidget", "Role change", None))
        self.role_cmbox.setItemText(0, _translate("SimulationWidget", "Procedural Enroute", None))
        self.role_cmbox.setItemText(1, _translate("SimulationWidget", "Radar Terminal", None))
        self.role_cmbox.setItemText(2, _translate("SimulationWidget", "Radar Arrivals", None))
        self.role_cmbox.setItemText(3, _translate("SimulationWidget", "Radar Departures", None))
        self.role_cmbox.setItemText(4, _translate("SimulationWidget", "Ground Procedural", None))
        self.role_cmbox.setItemText(5, _translate("SimulationWidget", "Local Procedural", None))
        self.label.setText(_translate("SimulationWidget", "Role", None))
        self.title_lbl.setText(_translate("SimulationWidget", "CALS Simulator", None))
        self.facility_lbl.setText(_translate("SimulationWidget", "Facility", None))
        self.workstationID_lbl.setText(_translate("SimulationWidget", "Workstation ID", None))

